services:
  - type: web
    name: weather-api
    env: python
    region: oregon
    buildCommand: "pip install -r python/requirements.txt"
    startCommand: "python python/weather_service.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health