services:
  - type: web
    name: weather-api
    runtime: python
    buildCommand: pip install -r python/requirements.txt
    startCommand: cd python && uvicorn weather_service:app --host 0.0.0.0 --port $PORT